MAIN_PAGE_DATA_TAG = 'Данные для главной страницы'
CALL_BACK_ACTION_BLOCK_CACHE_KEY = 'main_page:call_back_action_block'
FEATURES_CACHE_KEY = 'main_page:features'
HERO_ACTION_BLOCK_CACHE_KEY = 'main_page:hero_action_block'
MAIN_PAGE_FAQ_CACHE_KEY = 'main_page:faq'
MAIN_PAGE_SETTINGS_CACHE_KEY = 'main_page:settings'
