repos:
  - repo: local
    hooks:
      - id: ruff_check
        name: ruff check
        entry: python -m ruff check .
        exclude: /migrations/|wsgi.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: ruff_format
        name: ruff format
        entry: python -m ruff format .
        exclude: /migrations/|wsgi.py
        language: system
        types: [ python ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy . --ignore-missing-imports
        language: system
        types: [ python ]
