repos:
  - repo: local
    hooks:
      - id: ruff_check
        name: ruff check
        entry: app poetry run ruff check .
        exclude: /migrations/|wsgi.py
        language: docker_image
        types: [python]

  - repo: local
    hooks:
      - id: ruff_format
        name: ruff format
        entry: app poetry run ruff format .
        exclude: /migrations/|wsgi.py
        language: docker_image
        types: [ python ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: app poetry run mypy . --ignore-missing-imports
        language: docker_image
        types: [ python ]
