# Generated by Django 5.1.5 on 2025-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('action_text', models.CharField(max_length=200, verbose_name='Текст призыва')),
                ('short_description', models.CharField(max_length=400, verbose_name='Краткое описание')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('show_on_main_page', models.BooleanField(help_text='Показывать на сайте можно не более одного блока', verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Блок призыва к действию',
                'verbose_name_plural': 'Блоки призыва к действию',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='functions', verbose_name='Изображение')),
                ('image_url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Функция приложения',
                'verbose_name_plural': 'Функции приложения',
            },
        ),
        migrations.CreateModel(
            name='HeroActionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slogan', models.CharField(max_length=200, verbose_name='Слоган')),
                ('short_description', models.CharField(max_length=400, verbose_name='Краткое описание')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('show_on_main_page', models.BooleanField(help_text='Показывать на сайте можно не более одного блока', verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Блок слогана',
                'verbose_name_plural': 'Блоки слогана',
            },
        ),
        migrations.CreateModel(
            name='MainPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('question', models.CharField(max_length=400, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=400, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ для главной страницы',
                'verbose_name_plural': 'Вопросы-Ответы для главной страницы',
            },
        ),
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('max_slider_images', models.IntegerField(verbose_name='Максимальное количество изображений в слайдере')),
                ('max_advantages_count', models.IntegerField(verbose_name='Максимальное количество преимуществ')),
                ('max_functions_count', models.IntegerField(verbose_name='Максимальное количество функций')),
                ('max_reviews_count', models.IntegerField(verbose_name='Максимальное количество отзывов')),
                ('max_faqs_count', models.IntegerField(verbose_name='Максимальное количество ответов на вопросы (FAQ)')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главных страниц',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alt', models.CharField(max_length=100, verbose_name='Альтернативный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images', verbose_name='Изображение')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('show_on_main_page', models.BooleanField(verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Изображение в слайдере',
                'verbose_name_plural': 'Изображения в слайдере',
            },
        ),
    ]
