# Generated by Django 5.1.5 on 2025-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20250601_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionblock',
            name='action_text',
            field=models.CharField(max_length=200, unique=True, verbose_name='Текст призыва'),
        ),
        migrations.AlterField(
            model_name='calltoactionblock',
            name='short_description',
            field=models.CharField(max_length=400, unique=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='heroactionblock',
            name='short_description',
            field=models.CharField(max_length=400, unique=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='heroactionblock',
            name='show_on_main_page',
            field=models.BooleanField(default=False, help_text='Показывать на сайте можно не более одного блока', verbose_name='Показывать на главной странице'),
        ),
        migrations.AlterField(
            model_name='heroactionblock',
            name='slogan',
            field=models.CharField(max_length=200, unique=True, verbose_name='Слоган'),
        ),
    ]
