# Generated by Django 5.1.5 on 2025-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_alter_calltoactionblock_action_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='URL изображения'),
        ),
    ]
