# Generated by Django 5.1.5 on 2025-06-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_alter_sliderimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='image_url',
        ),
    ]
