# Generated by Django 5.1.5 on 2025-06-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_remove_sliderimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image_url',
        ),
    ]
