# Generated by Django 5.1.5 on 2025-02-07 19:55

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('patronymic_name', models.CharField(default='', max_length=150, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(validators=[core.validators.validate_not_future_date], verbose_name='Дата рождения')),
                ('diabetes_type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=5, verbose_name='Тип диабета')),
                ('diagnosis_date', models.DateField(blank=True, null=True, validators=[core.validators.validate_not_future_date], verbose_name='Дата постановки диагноза')),
                ('user', models.OneToOneField(help_text='Пользователь, к которому относится данный профиль', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ('updated_at',),
            },
        ),
    ]
