# Generated by Django 5.1.5 on 2025-02-09 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=500, verbose_name='Название болезни')),
                ('users', models.ManyToManyField(blank=True, help_text='Указанные пользователи болеют этим заболеванием', related_name='diseases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи с заболеванием')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
                'ordering': ['name'],
            },
        ),
    ]
