# Generated by Django 5.1.5 on 2025-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('1 типа', '1'), ('2 типа', '2'), ('MODY-диабет', 'MODY'), ('Гестационный диабет', 'gestational')], max_length=20, verbose_name='Тип диабета'),
        ),
    ]
