# Generated by Django 5.1.5 on 2025-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_userprofile_diabetes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
