# Generated by Django 5.1.5 on 2025-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('Инсулинотерапия', 'insulin_therapy'), ('Препараты', 'preparations')], default='', max_length=20, verbose_name='Тип лечения'),
        ),
    ]
