# Generated by Django 5.1.5 on 2025-02-09 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_userprofile_treatment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', '1-го типа'), ('2', '2-го типа'), ('mody', 'MODY-диабет'), ('gestational', 'Гестационный диабет')], max_length=20), blank=True, default=list, size=None, verbose_name='Тип диабета'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('insulin_therapy', 'Инсулинотерапия'), ('preparations', 'Препараты')], default='', max_length=20, verbose_name='Тип лечения'),
        ),
    ]
