# Generated by Django 5.1.5 on 2025-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_alter_userprofile_diabetes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('1', '1-го типа'), ('2', '2-го типа'), ('mody', 'MODY-диабет'), ('gestational', 'Гестационный диабет'), ('many_types', 'Несколько типов диабета')], max_length=20, verbose_name='Тип диабета'),
        ),
    ]
