# Generated by Django 5.1.5 on 2025-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_alter_userprofile_diabetes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes_type',
            field=models.CharField(blank=True, choices=[('1', '1-го типа'), ('2', '2-го типа'), ('mody', 'MODY-диабет'), ('gestational', 'Гестационный диабет'), ('many_types', 'Несколько типов диабета')], default='', max_length=20, verbose_name='Тип диабета'),
        ),
    ]
