# Generated by Django 5.1.5 on 2025-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_userprofile_image_alter_userprofile_diabetes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/stub.png', null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
