# Generated by Django 5.1.5 on 2025-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_advantage_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Показывать'),
        ),
    ]
