# Generated by Django 5.2.4 on 2025-07-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_alter_userprofile_diabetes_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
