# Generated by Django 5.2.4 on 2025-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг названия')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип лечения',
                'verbose_name_plural': 'Типы лечения',
                'ordering': ['name'],
            },
        ),
    ]
