# Generated by Django 5.2.4 on 2025-09-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_diabetestype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diabetestype',
            options={'ordering': ['id'], 'verbose_name': 'Тип диабета', 'verbose_name_plural': 'Типы диабета'},
        ),
        migrations.AlterModelOptions(
            name='treatmenttype',
            options={'ordering': ['id'], 'verbose_name': 'Тип лечения', 'verbose_name_plural': 'Типы лечения'},
        ),
    ]
