# Generated by Django 5.2.4 on 2026-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_alter_diabetestype_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='diabetestype',
            options={'ordering': ['name'], 'verbose_name': 'Тип диабета', 'verbose_name_plural': 'Справочник типов диабета'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Сопутствующее заболевание', 'verbose_name_plural': 'Справочник сопутствующих заболеваний'},
        ),
        migrations.AlterModelOptions(
            name='treatmenttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип лечения', 'verbose_name_plural': 'Справочник типов лечения'},
        ),
        migrations.RemoveField(
            model_name='diabetestype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='users',
        ),
        migrations.RemoveField(
            model_name='treatmenttype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
