# Generated by Django 5.2.4 on 2026-05-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_delete_advantage_remove_rate_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiabetesType',
        ),
        migrations.DeleteModel(
            name='TreatmentType',
        ),
    ]
