# Generated by Django 5.2.4 on 2025-07-28 15:31

import common_utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[common_utils.validators.validate_not_future_date], verbose_name='Дата рождения'),
        ),
    ]
