# Generated by Django 5.2.4 on 2025-08-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_appuser_birth_date'),
        ('cabinet', '0016_treatmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='treatment_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cabinet.treatmenttype', verbose_name='Тип лечения'),
        ),
    ]
