# Generated by Django 5.2.4 on 2025-08-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_appuser_treatment_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='treatment_type',
        ),
    ]
