# Generated by Django 5.2.4 on 2025-08-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_remove_appuser_treatment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='treatment_type_fk',
            new_name='treatment_type',
        ),
    ]
