# Generated by Django 5.2.4 on 2025-08-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_rename_treatment_type_fk_appuser_treatment_type'),
        ('cabinet', '0017_diabetestype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='diabetes_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cabinet.diabetestype', verbose_name='Тип диабета'),
        ),
    ]
