# Generated by Django 5.2.4 on 2025-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0006_appuser_diabetes_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='diabetes_type',
        ),
    ]
