# Generated by Django 5.2.4 on 2025-09-21 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0008_rename_diabetes_type_fk_appuser_diabetes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='height',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Рост'),
        ),
    ]
