# Generated by Django 5.2.4 on 2026-03-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0009_appuser_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('timedelta', models.IntegerField(verbose_name='Отклонение по часам')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Справочник городов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('undefined', 'Не определен')], default='undefined', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_service.town', verbose_name='Город'),
        ),
    ]
