# Generated by Django 5.2.4 on 2026-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0010_town_alter_appuser_gender_appuser_town'),
        ('data_tracking', '0018_mood_moodappuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='moods',
            field=models.ManyToManyField(related_name='users_with_mood', through='data_tracking.MoodAppUser', to='data_tracking.mood', verbose_name='Связанные настроения'),
        ),
    ]
