# Generated by Django 5.2.4 on 2026-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0011_appuser_moods'),
        ('cabinet', '0019_delete_advantage_remove_rate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='diseases',
            field=models.ManyToManyField(related_name='users_with_disease', to='cabinet.disease', verbose_name='Сопутствующие заболевания'),
        ),
    ]
