# Generated by Django 5.2.4 on 2026-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0012_appuser_diseases'),
        ('cabinet', '0019_delete_advantage_remove_rate_user_and_more'),
        ('data_tracking', '0019_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='users_with_disease', to='cabinet.disease', verbose_name='Сопутствующие заболевания'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='users_with_mood', through='data_tracking.MoodAppUser', to='data_tracking.mood', verbose_name='Связанные настроения'),
        ),
    ]
