# Generated by Django 5.2.4 on 2026-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0013_alter_appuser_diseases_alter_appuser_moods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='patronymic_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
