# Generated by Django 5.2.4 on 2026-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0014_alter_appuser_patronymic_name'),
        ('data_tracking', '0020_health_healthappuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='healths',
            field=models.ManyToManyField(blank=True, related_name='users_with_health', through='data_tracking.HealthAppUser', to='data_tracking.health', verbose_name='Связанные самочувствия'),
        ),
    ]
