# Generated by Django 5.2.4 on 2026-05-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0015_appuser_healths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='diabetes_type',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='treatment_type',
        ),
    ]
