# Generated by Django 5.1.5 on 2025-02-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('calories_count', models.PositiveSmallIntegerField(help_text='Количество калорий за день', verbose_name='Калории')),
                ('proteins_count', models.PositiveSmallIntegerField(help_text='Количество белков за день (в граммах)', verbose_name='Белки')),
                ('fats_count', models.PositiveSmallIntegerField(help_text='Количество жиров за день (в граммах)', verbose_name='Жиры')),
                ('carbs_count', models.PositiveSmallIntegerField(help_text='Количество углеводов за день (в граммах)', verbose_name='Углеводы')),
                ('general_health', models.CharField(choices=[('bad', 'Плохое'), ('normal', 'Нормальное'), ('great', 'Отличное'), ('tiredness', 'Усталость'), ('weakness', 'Слабость'), ('drowsiness', 'Сонливость'), ('dizziness', 'Головокружение'), ('nausea', 'Тошнота'), ('another', 'Другое')], default='normal', max_length=50, verbose_name='Общее самочувствие')),
                ('physical_activity', models.CharField(blank=True, default='', help_text='Запишите сюда, какой физической активностью вы сегодня занимались', max_length=2000, verbose_name='Физическая активность')),
                ('additional_info', models.CharField(blank=True, default='', max_length=2000, verbose_name='Дополнительная информация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дневной замер состояния',
                'verbose_name_plural': 'Дневные замеры состояния',
                'ordering': ['-updated_at'],
            },
        ),
    ]
