# Generated by Django 5.1.5 on 2025-02-09 14:26

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.FloatField(validators=[core.validators.validate_positive_float], verbose_name='Уровень глюкозы')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucoses', to='data_tracking.dailylog', verbose_name='Дневной замер состояния')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уровень глюкозы',
                'verbose_name_plural': 'Уровни глюкозы',
            },
        ),
    ]
