# Generated by Django 5.1.5 on 2025-02-11 18:16

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0003_pressure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucose',
            options={'verbose_name': 'Замер уровня глюкозы', 'verbose_name_plural': 'Замеры уровня глюкозы'},
        ),
        migrations.AlterModelOptions(
            name='pressure',
            options={'verbose_name': 'Замер давления', 'verbose_name_plural': 'Замеры давления'},
        ),
        migrations.AddField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата замера'),
        ),
        migrations.CreateModel(
            name='BodyTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('temperature', models.FloatField(validators=[core.validators.validate_positive_float], verbose_name='Температура тела')),
                ('daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_temperatures', to='data_tracking.dailylog', verbose_name='Дневной замер состояния')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Температура тела',
                'verbose_name_plural': 'Температуры тела',
            },
        ),
    ]
