# Generated by Django 5.1.5 on 2025-02-11 18:35

import common_utils.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0004_alter_glucose_options_alter_pressure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hemoglobin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Гликированный гемоглобин')),
                ('cholesterol', models.FloatField(blank=True, null=True, validators=[common_utils.validators.validate_positive_float], verbose_name='Уровень холестерина')),
                ('lipid_profile', models.FloatField(blank=True, null=True, validators=[common_utils.validators.validate_positive_float], verbose_name='Липидный профиль')),
                ('microalbuminuria', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Микроальбуминурия')),
                ('month', models.CharField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_log', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Месячный замер состояния',
                'verbose_name_plural': 'Месячные замеры состояния',
            },
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('bmi', models.PositiveSmallIntegerField(verbose_name='Индекс массы тела')),
                ('ketones', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Кетоны')),
                ('week_start', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала недели')),
                ('week_end', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания недели')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Еженедельный отчет',
                'verbose_name_plural': 'Еженедельные отчеты',
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weekly_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_tracking.weeklylog', verbose_name='Месячный отчет'),
        ),
    ]
