# Generated by Django 5.1.5 on 2025-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0005_monthlylog_weeklylog_dailylog_weekly_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlylog',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=10, verbose_name='Месяц'),
        ),
    ]
