# Generated by Django 5.1.5 on 2025-04-05 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0008_alter_dailylog_weekly_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylog',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Год'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlylog',
            unique_together={('user', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('user', 'week_start', 'week_end')},
        ),
    ]
