# Generated by Django 5.1.5 on 2025-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0009_monthlylog_year_alter_monthlylog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='bmi',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Индекс массы тела'),
        ),
    ]
