# Generated by Django 5.1.5 on 2025-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0010_alter_weeklylog_bmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название настроения')),
                ('color', models.CharField(help_text='Tailwind-класс', max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроения',
            },
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='general_health',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='mood',
            field=models.SmallIntegerField(choices=[(1, 'Ужасное'), (2, 'Плохое'), (3, 'Нормальное'), (4, 'Хорошее'), (5, 'Прекрасное')], default=3, verbose_name='Настроение'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='health',
            field=models.ManyToManyField(blank=True, related_name='daily_logs', to='data_tracking.health', verbose_name='Самочувствие'),
        ),
    ]
