# Generated by Django 5.2.4 on 2025-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0011_health_remove_dailylog_general_health_dailylog_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='Tailwind-класс', max_length=50, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='health',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Tailwind-класс', max_length=50, verbose_name='Цвет'),
        ),
    ]
