# Generated by Django 5.2.4 on 2025-09-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0012_health_bg_color_alter_health_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Health',
            new_name='Mood',
        ),
    ]
