# Generated by Django 5.2.4 on 2025-09-18 16:16

from django.db import migrations


MOODS = [
    {
        'name': 'Злой',
        'color': 'text-red-700',
        'bg_color': 'bg-red-100',
    },
    {
        'name': 'Весёлый',
        'color': 'text-yellow-600',
        'bg_color': 'bg-yellow-100',
    },
    {
        'name': 'Спокойный',
        'color': 'text-blue-700',
        'bg_color': 'bg-blue-100',
    },
    {
        'name': 'Грустный',
        'color': 'text-indigo-700',
        'bg_color': 'bg-indigo-100',
    },
    {
        'name': 'Вдохновлённый',
        'color': 'text-emerald-700',
        'bg_color': 'bg-emerald-100',
    },
    {
        'name': 'Уставший',
        'color': 'text-gray-600',
        'bg_color': 'bg-gray-100',
    },
    {
        'name': 'Влюблённый',
        'color': 'text-pink-700',
        'bg_color': 'bg-pink-100',
    },
    {
        'name': 'Тревожный',
        'color': 'text-orange-700',
        'bg_color': 'bg-orange-100',
    },
    {
        'name': 'Уверенный',
        'color': 'text-teal-700',
        'bg_color': 'bg-teal-100',
    },
    {
        'name': 'Загадочный',
        'color': 'text-purple-700',
        'bg_color': 'bg-purple-100',
    },
]


def create_mood_instances(apps, schema_editor):
    """Создать объекты для модели Mood"""
    Mood = apps.get_model('data_tracking', 'Mood')
    Mood.objects.bulk_create(
        [Mood(**mood) for mood in MOODS]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0013_rename_health_mood'),
    ]

    operations = [
        migrations.RunPython(create_mood_instances, migrations.RunPython.noop),
    ]
