# Generated by Django 5.2.4 on 2026-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0014_auto_20250918_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlylog',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026, verbose_name='Год'),
        ),
    ]
