# Generated by Django 5.2.4 on 2026-03-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0015_alter_monthlylog_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='health',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='weekly_log',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='daily_log',
        ),
        migrations.RemoveField(
            model_name='glucose',
            name='daily_log',
        ),
        migrations.RemoveField(
            model_name='glucose',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='monthlylog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weeklylog',
            name='monthly_log',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='BodyTemperature',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='Glucose',
        ),
        migrations.DeleteModel(
            name='MonthlyLog',
        ),
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='WeeklyLog',
        ),
    ]
