# Generated by Django 5.2.4 on 2026-03-04 16:27

import common_utils.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_tracking', '0016_alter_dailylog_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (моль/л)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение холестерина',
                'verbose_name_plural': 'Значения холестерина',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_099c64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (ммоль/л)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение уровня сахара в крови',
                'verbose_name_plural': 'Значения уровня сахара в крови',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_1d9840_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hemoglobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение (г/л)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение гемоглобина',
                'verbose_name_plural': 'Значения гемоглобина',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_108dcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ketones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (ммоль/л)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение кетонов',
                'verbose_name_plural': 'Значения кетонов',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_fe96e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LipidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (ммоль/л)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение липидного профиля',
                'verbose_name_plural': 'Значения липидного профиля',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_bc13de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('calories', models.PositiveSmallIntegerField(verbose_name='Калории')),
                ('proteins', models.PositiveSmallIntegerField(verbose_name='Белки')),
                ('carbs', models.PositiveSmallIntegerField(verbose_name='Жиры')),
                ('fats', models.PositiveSmallIntegerField(verbose_name='Углеводы')),
                ('eaten_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время приема пищи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение ЛБЖУ за прием пищи',
                'verbose_name_plural': 'Значения ЛБЖУ за прием пищи',
                'indexes': [models.Index(fields=['user', 'eaten_at'], name='data_tracki_user_id_131461_idx')],
            },
        ),
        migrations.CreateModel(
            name='Microalbuminuria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (мг/сут)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение микроальбуминурии',
                'verbose_name_plural': 'Значения микроальбуминурии',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_b7ff9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_711ad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись о физической активности',
                'verbose_name_plural': 'Записи о физической активности',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_0d04a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.FloatField(validators=[common_utils.validators.validate_positive_float], verbose_name='Значение (в Цельсия)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение температуры',
                'verbose_name_plural': 'Значения температуры',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_2c98c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение (кг)')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Значение веса',
                'verbose_name_plural': 'Значения веса',
                'indexes': [models.Index(fields=['user', 'measured_at'], name='data_tracki_user_id_830af5_idx')],
            },
        ),
    ]
