# Generated by Django 5.2.4 on 2026-03-04 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0017_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('text_color', models.CharField(help_text='TailwindCSS-стиль', max_length=20, verbose_name='Цвет')),
                ('background_color', models.CharField(help_text='TailwindCSS-стиль', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Справочник настроений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_tracking.mood', verbose_name='Настроение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка пользователя и настроения',
                'verbose_name_plural': 'Связки пользователя и настроения',
                'indexes': [models.Index(fields=['user', 'mood', 'measured_at'], name='data_tracki_user_id_e4f34c_idx')],
            },
        ),
    ]
