# Generated by Django 5.2.4 on 2026-03-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0018_mood_moodappuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Значение КБЖУ за прием пищи', 'verbose_name_plural': 'Значения КБЖУ за прием пищи'},
        ),
    ]
