# Generated by Django 5.2.4 on 2026-03-07 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0020_health_healthappuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('systolic', models.PositiveSmallIntegerField(verbose_name='Систолическое')),
                ('diastolic', models.PositiveSmallIntegerField(verbose_name='Диастолическое')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время замера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Замер давления',
                'verbose_name_plural': 'Замеры давления',
            },
        ),
    ]
