# Generated by Django 5.2.4 on 2026-04-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0021_pressure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('taken_at', models.DateTimeField(verbose_name='Время приема')),
                ('dose', models.FloatField(verbose_name='Дозировка')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_tracking.medication', verbose_name='Лекарство из справочника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прием лекарства',
                'verbose_name_plural': 'Приемы лекарств',
            },
        ),
    ]
