# Generated by Django 5.2.4 on 2026-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0022_medication_medicationtake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='health',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='text_color',
        ),
        migrations.AddField(
            model_name='health',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='mood',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='health',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
