# Generated by Django 5.2.4 on 2026-05-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0024_alter_health_slug_alter_mood_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cholesterol',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение холестерина', 'verbose_name_plural': 'Значения холестерина'},
        ),
        migrations.AlterModelOptions(
            name='glucose',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение уровня сахара в крови', 'verbose_name_plural': 'Значения уровня сахара в крови'},
        ),
        migrations.AlterModelOptions(
            name='hemoglobin',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение гемоглобина', 'verbose_name_plural': 'Значения гемоглобина'},
        ),
        migrations.AlterModelOptions(
            name='ketones',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение кетонов', 'verbose_name_plural': 'Значения кетонов'},
        ),
        migrations.AlterModelOptions(
            name='lipidprofile',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение липидного профиля', 'verbose_name_plural': 'Значения липидного профиля'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-eaten_at'], 'verbose_name': 'Значение КБЖУ за прием пищи', 'verbose_name_plural': 'Значения КБЖУ за прием пищи'},
        ),
        migrations.AlterModelOptions(
            name='medicationtake',
            options={'ordering': ['-taken_at'], 'verbose_name': 'Прием лекарства', 'verbose_name_plural': 'Приемы лекарств'},
        ),
        migrations.AlterModelOptions(
            name='microalbuminuria',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение микроальбуминурии', 'verbose_name_plural': 'Значения микроальбуминурии'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='physicalactivity',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Запись о физической активности', 'verbose_name_plural': 'Записи о физической активности'},
        ),
        migrations.AlterModelOptions(
            name='pressure',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Замер давления', 'verbose_name_plural': 'Замеры давления'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение температуры', 'verbose_name_plural': 'Значения температуры'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-measured_at'], 'verbose_name': 'Значение веса', 'verbose_name_plural': 'Значения веса'},
        ),
    ]
